version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wyze-bridge_web_1
      APP_PORT: 4444
  web:
    image: mrlt8/wyze-bridge:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 1935:1935 # RTMP
      - 8554:8554 # RTSP
      - 8888:8888 # HLS
      - 5000:5000 # webui
    volumes:
       - ${APP_DATA_DIR}/recordings:/record/
    environment:
      #- WYZE_EMAIL=<email>
      #- WYZE_PASSWORD=<pw>
      - TZ=America/Toronto
      - RECORD_ALL=True
      - RECORD_LENGTH=600
      - ENABLE_AUDIO=True