version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: shiobi_web_1
      APP_PORT: 8080

  web:
    image: registry.gitlab.com/shinobi-systems/shinobi:dev
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/customAutoLoad:/home/Shinobi/libs/customAutoLoad
      - ${APP_DATA_DIR}/database:/var/lib/mysql
      - ${APP_DATA_DIR}/recordings:/home/Shinobi/videos
      - ${APP_DATA_DIR}/plugins:/home/Shinobi/plugins
      - ${APP_DATA_DIR}/streams:/dev/shm/streams

    expose:
      - "8080"

    environment:
      - PLUGIN_KEYS={}
      - SSL_ENABLED=false
